SELECT
    CAR_ID
    ,CAR_TYPE
    ,FEE
FROM (
    SELECT
        C.CAR_ID
        ,C.CAR_TYPE
        , ROUND(C.DAILY_FEE * (100 - P.DISCOUNT_RATE) * 0.01 * 30) AS FEE
    FROM CAR_RENTAL_COMPANY_CAR C
    INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
    ON C.CAR_TYPE = P.CAR_TYPE
    AND P.DURATION_TYPE = '30일 이상'

    WHERE C.CAR_TYPE IN ('세단' ,'SUV')
    AND C.CAR_ID NOT IN (
        SELECT
            CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
        WHERE H.START_DATE <= TO_DATE('2022-11-30', 'YYYY-MM-DD')
        AND H.END_DATE >= TO_DATE('2022-11-01', 'YYYY-MM-DD')
    )
) T
WHERE FEE >= 500000
AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC