-- 코드를 작성해주세요
SELECT
    ED.ID
   , CASE 
        WHEN P.PERCENT <= 25 THEN 'CRITICAL'
        WHEN P.PERCENT <=50 THEN 'HIGH'
        WHEN P.PERCENT <=75 THEN 'MEDIUM'
        ELSE 'LOW'
   END AS COLONY_NAME
FROM ECOLI_DATA ED
LEFT OUTER JOIN (
    SELECT
        ID
        , PERCENT_RANK() OVER(ORDER BY SIZE_OF_COLONY DESC) *100 AS PERCENT
    FROM ECOLI_DATA
) p
ON P.ID = ED.ID
ORDER BY ED.ID