-- 코드를 입력하세요
SELECT
    CAR_ID
    ,TO_CHAR(AVERAGE_DURATION1, 'FM9990.0') AS AVERAGE_DURATION
FROM (
    SELECT
        CAR_ID
        ,ROUND(AVG(END_DATE - START_DATE + 1), 1) AS AVERAGE_DURATION1
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    GROUP BY CAR_ID
) T
WHERE AVERAGE_DURATION1 >= 7
ORDER BY AVERAGE_DURATION1 DESC, CAR_ID DESC