-- 코드를 입력하세요
WITH CTE_P AS (
    SELECT
        HOST_ID
    FROM PLACES
    GROUP BY HOST_ID
    HAVING COUNT(ID) > 1
)
SELECT
    ID, NAME, HOST_ID
FROM PLACES
WHERE HOST_ID IN (
    SELECT HOST_ID FROM CTE_P
)
ORDER BY ID