-- 코드를 입력하세요
SELECT
    H.HISTORY_ID
    , CASE
        WHEN P.DISCOUNT_RATE IS NULL THEN C.DAILY_FEE
        ELSE C.DAILY_FEE * ( 1 - P.DISCOUNT_RATE / 100)
    END * (END_DATE - START_DATE + 1) AS FEE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
INNER JOIN CAR_RENTAL_COMPANY_CAR C
ON C.CAR_ID = H.CAR_ID
LEFT OUTER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON P.CAR_TYPE = C.CAR_TYPE
AND P.DURATION_TYPE = CASE
                        WHEN (END_DATE - START_DATE + 1) >= 90 THEN '90일 이상'
                        WHEN (END_DATE - START_DATE + 1) >= 30 THEN '30일 이상'
                        WHEN (END_DATE - START_DATE + 1) >= 7 THEN '7일 이상'
                    END
WHERE C.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC