-- 코드를 입력하세요
WITH RECURSIVE CTE_HOUR AS
(
  SELECT 0 AS HH
  UNION ALL
  SELECT 1+HH FROM CTE_HOUR WHERE HH < 23  # <- recursive SELECT
)


SELECT
    CH.HH
    ,IFNULL(AO.COUNT, 0) AS COUNT
FROM CTE_HOUR CH
LEFT OUTER JOIN (
    SELECT
        DATE_FORMAT(DATETIME, '%H') AS HH
        ,COUNT(ANIMAL_ID) AS COUNT
    FROM ANIMAL_OUTS AO
    GROUP BY DATE_FORMAT(DATETIME, '%H')
) AO
ON CH.HH = AO.HH