-- 코드를 입력하세요
SELECT
    MP.MEMBER_NAME
    ,RR.REVIEW_TEXT
    ,DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MP
INNER JOIN REST_REVIEW RR
ON RR.MEMBER_ID = MP.MEMBER_ID
INNER JOIN (
    SELECT
        RR.MEMBER_ID
        ,DENSE_RANK() OVER(ORDER BY COUNT(RR.REVIEW_ID) DESC) AS DR
    FROM REST_REVIEW RR
    GROUP BY RR.MEMBER_ID
) RR_DR
ON RR_DR.DR = 1
AND RR_DR.MEMBER_ID = MP.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT