-- 코드를 입력하세요



SELECT 
    --HISTORY_ID
    --, CAR_ID
    --, START_DATE
    --, END_DATE
    LTRIM(TO_CHAR(START_DATE, 'MM'), '0')*1 AS MONTH
    , CAR_ID
    , COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (
    SELECT
        CAR_ID AS TOTAL_CAR_ID
        ,COUNT(CAR_ID) AS TOTAL_CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
    AND START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD') 
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)B
ON A.CAR_ID = B.TOTAL_CAR_ID
WHERE START_DATE >= TO_DATE('2022-08-01', 'YYYY-MM-DD')
AND START_DATE < TO_DATE('2022-11-01', 'YYYY-MM-DD')
GROUP BY TO_CHAR(START_DATE, 'MM')
        , CAR_ID
ORDER BY 1, 2 DESC