-- 코드를 입력하세요
SELECT
    TRIM(LEADING '0' FROM DATE_FORMAT(START_DATE, '%m'))*1 AS MONTH
    , CAR_ID
    , COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
INNER JOIN (
    SELECT
        CAR_ID AS TOTAL_CAR_ID
        ,COUNT(CAR_ID) AS TOTAL_CNT
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31' 
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)B
ON A.CAR_ID = B.TOTAL_CAR_ID
WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY DATE_FORMAT(START_DATE, '%m')
        , CAR_ID
ORDER BY 1, 2 DESC