-- 코드를 작성해주세요
SELECT
    YEAR(ED.DIFFERENTIATION_DATE) AS YEAR
    ,GRUP.MAX_SIZE_OF_COLONY - ED.SIZE_OF_COLONY AS YEAR_DEV
    ,ED.ID
FROM ECOLI_DATA ED
INNER JOIN (
    SELECT
        YEAR(DIFFERENTIATION_DATE) AS YYYY
        ,MAX(SIZE_OF_COLONY) AS MAX_SIZE_OF_COLONY
    FROM ECOLI_DATA 
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) GRUP
ON GRUP.YYYY = YEAR(ED.DIFFERENTIATION_DATE)
ORDER BY YEAR, YEAR_DEV