-- 코드를 입력하세요
SELECT DISTINCT
    CRCC.CAR_ID
FROM CAR_RENTAL_COMPANY_CAR CRCC
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY CRCRH  
ON CRCRH.CAR_ID = CRCC.CAR_ID
WHERE CRCC.CAR_TYPE = '세단'
AND EXTRACT(MONTH FROM CRCRH.START_DATE) = '10'
ORDER BY CAR_ID DESC