-- 코드를 작성해주세요
SELECT
    HRE.DEPT_ID
    ,(
        SELECT
            HRD.DEPT_NAME_EN
        FROM HR_DEPARTMENT HRD
        WHERE HRD.DEPT_ID = HRE.DEPT_ID
    ) AS DEPT_NAME_EN
    ,ROUND(AVG(HRE.SAL), 0) AS AVG_SAL
FROM HR_EMPLOYEES HRE
GROUP BY HRE.DEPT_ID
ORDER BY AVG_SAL DESC