-- 코드를 입력하세요
SELECT
    CONCAT('/home/grep/src/', B.BOARD_ID , '/', F.FILE_ID, F.FILE_NAME, F.FILE_EXT) AS FILE_PATH
FROM (
    SELECT
        BOARD_ID
        ,RANK() OVER(ORDER BY VIEWS DESC) AS RANK_VIEW
    FROM USED_GOODS_BOARD
) B
INNER JOIN USED_GOODS_FILE F
ON B.BOARD_ID = F.BOARD_ID
WHERE B.RANK_VIEW = 1
ORDER BY F.FILE_ID DESC