-- 코드를 입력하세요
SELECT
    B.CATEGORY
    ,SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES S
INNER JOIN BOOK B
ON B.BOOK_ID = S.BOOK_ID
WHERE S.SALES_DATE BETWEEN TO_DATE('20220101', 'YYYYMMDD') AND TO_DATE('20220131', 'YYYYMMDD')
GROUP BY B.CATEGORY
ORDER BY CATEGORY